lang: c
env:
  - secure: "OKG83uTOFHfHbxrd8nN5JRVLGirXL/Kjto6UBi0wLi7GpC452nL0P87XQlVI\n+G27H0p38vbZ6WxHoLadu2dW+B4T/J5maPmSZPE4CZVbOORjAx/8fV3SYoBn\nj12ZNEgORkOSqVvnDBxJLDhzwZeVwiFsJcJ9H5S+3PmYIZrX4C0="
script: ./travis-ci.sh
notifications:
  irc:
    - "irc.freenode.org#rerun"
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq markdown
 - sudo apt-get install -qq build-essential
 - sudo apt-get install -qq devscripts
 - sudo apt-get install -qq dh-make    
 - sudo apt-get install -qq rpm    
