lang: c
env:
  matrix:
  - secure: |-
      OKG83uTOFHfHbxrd8nN5JRVLGirXL/Kjto6UBi0wLi7GpC452nL0P87XQlVI
      +G27H0p38vbZ6WxHoLadu2dW+B4T/J5maPmSZPE4CZVbOORjAx/8fV3SYoBn
      j12ZNEgORkOSqVvnDBxJLDhzwZeVwiFsJcJ9H5S+3PmYIZrX4C0=
  - secure: E502IZED9dqcN+NdLf8pkQxGbB+k4nxekOjRba0Is6AnHbzRfqG+qh90PbcMFyxGzub8Akv8O3XoyfokPviqJA67ePdhFY6mSmz4jTTg29Dg41WVv1ljYOr+dwp52zTEN0mAOid9Dcz7Ifa5NDpVNExDuwiOgbp225HxqFY3K0A=
script: "./travis-ci.sh"
notifications:
  irc:
  - irc.freenode.org#rerun
before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq markdown
- sudo apt-get install -qq build-essential
- sudo apt-get install -qq devscripts
- sudo apt-get install -qq dh-make
- sudo apt-get install -qq rpm
